### ISSUE TITLE
There are two cursors blinking in the player field.

### ISSUE THREAD

**Issue by MilanNL** [stickyPiston/data-plumber#13]
While testing data-plumber, I found two cursors blinking in the player field.

**Comment by stickyPiston** [comment]
Thank you for creating an issue, now I won't forget to do this. If you'd ever find any other bugs or you'd want to suggest a new feature, create a new issue. :)

**Comment by stickyPiston** [comment]
I've created a review request for #15. Could you check whether the bug is fixed...

**Comment by stickyPiston** [comment]
PR #15 is merged. Closing issue...
